{% set name = "telegram-send" %}
{% set version = "0.34" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 291f6653c16f03ebcecf81422258eb164f5708db610bc779e687f93ed6bfa324

build:
  number: 0
  entry_points:
    - telegram-send=telegram_send:main
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - appdirs
    - colorama
    - python >=3.6
    - python-telegram-bot >=12.1.1

test:
  commands:
    - telegram-send --help

about:
  home: https://github.com/rahiel/telegram-send
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE.txt
  summary: Send messages and files over Telegram from the command-line.
  dev_url: https://github.com/rahiel/telegram-send

extra:
  recipe-maintainers:
    - proinsias
